### ISSUE TITLE
Error #2048: Security sandbox violation

### ISSUE THREAD

**Issue by Eketol** [myflashlab/AS3-youtube-parser-video-link#1]
Hi, I tried your code to retrieve the video title. I've created a test SWF and it works nice when running from my local machine, but when I upload it to the server I get:
Error #2048: Security sandbox violation: cannot load data from http://www.youtube.com/get_video_info?&video_id=y1Rx-Bbht5E&asv=3&el=detailpage&hl=en_US.
I understand this is meant to be used in Adobe Air applications. Is there something I can do to get it working from a server? Thanks.

**Comment by myflashlab** [comment]
We really have not used it as a flash project and its been years that we
don't do flash browser projects anyway. As you suggested yourself though,
this won't be a problem on AdobeAir.
