### ISSUE TITLE
URLRequest needs to be updated.

### ISSUE THREAD

**Issue by Gohloum** [myflashlab/AS3-youtube-parser-video-link#2]
Current code is attempting to use properties that do not exist (YouTubeLinkParser class):

`
request.userAgent = "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:8.0.1)";
request.method = URLRequestMethod.POST;
request.manageCookies = true;
`

Tried replacing with the following code, which does allow to compile and run, but Youtube rejects the request and returns and I/O error

`
request.requestHeaders = [];
request.requestHeaders.push(new URLRequestHeader("userAgent", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:8.0.1)"));
request.requestHeaders.push(new URLRequestHeader("method", URLRequestMethod.POST));
request.requestHeaders.push(new URLRequestHeader("manageCookies", "true"));
`

**Comment by myflashlab** [comment]
Not correct. These classes and methods are all working fine. You are probably testing this on Flash for browser? If that's the case, well, it's not working. This library works on AIR content only. on Android, iOS, desktop apps for windows and mac.

**Comment by Gohloum** [comment]
Hello,

No, I didn’t build locally, I am aware ANE files don’t work that way.  I tried once building to my iPhone via USB and then I sent a second build through TestFlight.  Neither of them worked.  When bugging via USB, it seems to just stall and never streams the video. 

Currently I am on another project. Once I am back on this project, I can send you screenshots and trace data while debugging via USB if that would help. 

Thanks!

TJ Jones
tjones@tangerinepop.com
Tangerine Pop Game LLC
http://www.tangerinepop.com

**Comment by myflashlab** [comment]
Ok, I am somehow confused now!

1. This library is NOT an ANE, it's a pure AS3 code.
2. build locally? What do you mean by that?
3. I don't understand the relation between installing via USB/TestFlight and this library!

All this library does is to parse a youtube link and find the direct video links for you to download. That's all it does.

**Comment by myflashlab** [comment]
you also said "Current code is attempting to use properties that do not exist" what AIR SDK are you using?! these properties have been with AIR for a VERY LONG time.

**Comment by Gohloum** [comment]
OK, let me try and clear this up, sorry for the confusion.  I am currently using IntelliJ as my IDE.  I'm using AIR 24 SDK with Starling 2.x  and Feathers 3.x.  These are packaged together by Josh and you can see more details here: https://feathersui.com/sdk/

Regardless of what build configurations I use (desktop, AIR mobile, or Android), I get the following compile errors:

/Users/tjones_mbp/ActionScriptLibraries/MyFlashLabClub_ANEs_package/ANEs/AS3-youtube-parser-video-link/src/com/doitflash/remote/youtube/YouTubeLinkParser.as
Error:(230, 12) [PopCards_AP_Math Desktop (module PopCards_AP_Math)]: Error code: 1119: Access of possibly undefined property userAgent through a reference with static type flash.net:URLRequest.
Error:(232, 12) [PopCards_AP_Math Desktop (module PopCards_AP_Math)]: Error code: 1119: Access of possibly undefined property manageCookies through a reference with static type flash.net:URLRequest.
Error:(280, 12) [PopCards_AP_Math Desktop (module PopCards_AP_Math)]: Error code: 1119: Access of possibly undefined property userAgent through a reference with static type flash.net:URLRequest.

Therefore, I can't even compile because of these lines of code.  However, if I exclude your library, the app runs fine on iOS.  In fact, version 1 is on the app store.

To attempt to workaround, I tried modifying the code as stated in my first post. However, it fails on the response which I thought it might, but was worth trying.

OK to address your comments above:

"This library is NOT an ANE, it's a pure AS3 code." -  Yes, I know. However i was trying to use it with your videoplayer which is an ANE and will not run locally on the ADL emulator, it must be run on a mobile device.

build locally? What do you mean by that? - Meaning I was not running on the ADL on my macbook, I was compiling it to my iPhone directly across USB.
    
I don't understand the relation between installing via USB/TestFlight and this library! - Testflight is a way to distribute a test build through iTunesConnect.  See Apple's documentation for further details.

**Comment by Gohloum** [comment]
Did another quick check in my compiler settings and the airglobal.swc is merged into my code.  Just wanted to make sure, although, I don't believe I could build to iOS in the first place if it wasn't included.  Specific AIR version is 24.0.0.180

**Comment by myflashlab** [comment]
Considering that you are using intelliJ, I created this sample project for you. It's a desktop app. You must be able to retrieve the video link in trace logs. Let me know how it goes.

[Archive.zip](https://github.com/myflashlab/AS3-youtube-parser-video-link/files/1341030/Archive.zip)

**Comment by Gohloum** [comment]
Awesome! Thank you!  I will need a few days to get to it, but I will post my results once I have a chance to run it.
